import java.sql.SQLException;

public class testlogin {
    public static void main(String[] args) throws SQLException {

//        Users user = new Users();
//        UserDao userDao = new UserDao();
//        List<Users> list = userDao.selectByMany("admin", "111111", "2005-1-1");
//        System.out.println(list.size());
//        for (int i = 0; i < list.size(); i++) {
//            System.out.println(list.get(i));
//        }

//        Users user = new Users();
//        user.setUid(3);
//        user.setUpwd("123321");
//        user.setUname("qyf");
//        user.setUbirthday("10000");
//        user.setUanswer("");
//        user.setUemail("asd");
//        user.setUgender(true);
//        user.setUhobby("");
//        user.setUimage("");
//        user.setUphonenumber("");
//        user.setUquestion("");
//        user.setUsign("");
//        UserDao userDao = new UserDao();
//        userDao.update(user);

//        Relationship relationship = new Relationship();
//        RelationshipDao dao = new RelationshipDao();
//        relationship.setRid(3);
//        relationship.setRuid(3);
//        relationship.setRfiendid(3);
//        relationship.setRtype(1);
//        relationship.setRdate("2220");
//        dao.update(relationship);
//        List<Relationship> list = dao.selectByRuid(3);
//        System.out.println(list);



    }
}
